# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: matrix.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'matrix.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmatrix.proto\x12\x06matrix\"*\n\nLineColumn\x12\x0c\n\x04line\x18\x01 \x03(\x05\x12\x0e\n\x06\x63olumn\x18\x02 \x03(\x05\"8\n\x06Result\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t2?\n\rMatrixService\x12.\n\x08Multiply\x12\x12.matrix.LineColumn\x1a\x0e.matrix.Resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'matrix_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LINECOLUMN']._serialized_start=24
  _globals['_LINECOLUMN']._serialized_end=66
  _globals['_RESULT']._serialized_start=68
  _globals['_RESULT']._serialized_end=124
  _globals['_MATRIXSERVICE']._serialized_start=126
  _globals['_MATRIXSERVICE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
